flasksystem/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError

class ModBajoStockForm(FlaskForm):
    bajo_stock = IntegerField(validators=[DataRequired()])
    submit = SubmitField('Ingresa')
    
    def validate_bajo_stock(self, bajo_stock):
        if bajo_stock.data <= 0:
            raise ValidationError('Ingresa una cantidad mayor a 0')
 

flasksystem/materias/forms.py
from flasksystem import db
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError
from flasksystem.models import Medida, Materia

class MateriaForm(FlaskForm):
    nombre = StringField('Nombre', validators=[DataRequired(), Length(max=100)])
    codigo = StringField('Codigo', validators=[DataRequired(), Length(max=30)])
    medida = SelectField("Medidas", choices=Medida.choices(), coerce=Medida.coerce)
    bajo_stock = IntegerField('Bajo Stock', validators=[DataRequired()])
    # foo = SelectField('Foo', coerce=int, choices=[(1, 'Foo 1'), (2, 'Foo 2')])
    submit = SubmitField('Ingresar')
    
    def validate_bajo_stock(self, bajo_stock):
        if bajo_stock.data <= 0:
            raise ValidationError('Ingresa una cantidad mayor a 0')

class AddMateriaForm(FlaskForm):
    cantidad = IntegerField(validators=[DataRequired()])
    observacion = StringField('Observacion', validators=[Length(max=100)])
    submit = SubmitField('Ingresar')

    def validate_cantidad(self, cantidad):
        if cantidad.data <= 0:
            raise ValidationError('Ingresa una cantidad mayor a 0')

class ReduceMateriaForm(FlaskForm):
    cantidad = IntegerField(validators=[DataRequired()])
    observacion = StringField('Observacion', validators=[Length(max=100)])
    submit = SubmitField('Ingresar')

    def validate_cantidad(self, cantidad):
        if cantidad.data <= 0:
            raise ValidationError('Ingresa una cantidad mayor a 0')

flasksystem/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flasksystem.config import Config
from flask_migrate import Migrate, MigrateCommand
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
migrate = Migrate()
ma = Marshmallow()

login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'

from flasksystem.main.routes import main
from flasksystem.materias.routes import materias
from flasksystem.reactivos.routes import reactivos
from flasksystem.users.routes import users
from flasksystem.errors.handlers import errors


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    ma.init_app(app)

    app.register_blueprint(main)
    app.register_blueprint(materias)
    app.register_blueprint(reactivos)
    app.register_blueprint(users)
    app.register_blueprint(errors)

    return app

flasksystem/main/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import current_user, login_required
from flasksystem.models import HistorialQuimicos, Quimico, Area
from flasksystem.main.utils import check_lab, check_bod

main = Blueprint('main', __name__)

@main.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    return render_template('index.html')

@main.route("/home")
@login_required
def home():
    if current_user.area == Area.Lab.value:
        return redirect(url_for('main.lab_home'))
    elif current_user.area == Area.Bod.value:
        return redirect(url_for('main.bod_home'))
    else:
        return render_template('home.html', title='Home')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/home/historial")
@login_required
def home_historial():
    historiales = HistorialQuimicos.query.order_by(HistorialQuimicos.fecha_registro.desc()).all()
    return render_template('ver_historial.html', historiales=historiales)

@main.route("/lab")
@login_required
def lab_home():
    check_lab()
    quimicos = Quimico.query.filter_by(area=Area.Lab.value).all()
    return render_template('lab/home.html', title='Lab Home', quimicos=quimicos, area='Lab', user=current_user)

@main.route("/lab/historial")
@login_required
def lab_home_historial():
    check_lab()
    historiales = HistorialQuimicos.query.filter_by(area=Area.Lab.value).order_by(HistorialQuimicos.fecha_registro.desc()).all()
    return render_template('ver_historial.html', historiales=historiales, area='Lab')

@main.route("/bod")
@login_required
def bod_home():
    check_bod()
    quimicos = Quimico.query.filter_by(area=Area.Bod.value).all()
    return render_template('bod/home.html', title='Bod Home', quimicos=quimicos, area='Bod', user=current_user)

@main.route("/bod/historial")
@login_required
def bod_home_historial():
    check_bod()
    historiales = HistorialQuimicos.query.filter_by(area=Area.Bod.value).order_by(HistorialQuimicos.fecha_registro.desc()).all()
    return render_template('ver_historial.html', historiales=historiales, area='Bod')

flasksystem/materias/routes.py
from flask import render_template, url_for, flash, redirect, abort, jsonify, request, Blueprint
from flask_login import current_user, login_required
from flasksystem import db
from flasksystem.models import Materia, HistorialMaterias, Quimico, HistorialQuimicos, Area
from flasksystem.materias.forms import MateriaForm, AddMateriaForm, ReduceMateriaForm
from flasksystem.main.utils import check_bod, check_lab, check_only_bod, check_only_lab
from flasksystem.main.forms import ModBajoStockForm
from flasksystem.schema import (materia_schema, materias_schema, historial_materia_schema, historiales_materia_schema,
                                quimico_schema, quimicos_schema, historial_quimico_schema, historiales_quimico_schema,
                                materia_bajo_stock_schema)
from flasksystem.users.routes import token_required
from marshmallow import ValidationError

materias = Blueprint('materias', __name__)

# --------------------------------SECTOR DE ROUTES LABORATORIO----------------------------------------------

@materias.route("/lab/materia/create", methods=['GET', 'POST'])
@login_required
def lab_new_materia():
    check_only_lab()
    form = MateriaForm()
    if form.validate_on_submit():
        materia = Materia(nombre=form.nombre.data, codigo=form.codigo.data, medida=form.medida.data, 
                            bajo_stock=form.bajo_stock.data, area=Area.Lab.value)
        db.session.add(materia)
        db.session.commit()
        quimico = Quimico(tipo='Materia', materia=materia, area=Area.Lab.value)
        db.session.add(quimico)
        db.session.commit()        
        flash('La materia se ha creado exitosamente!', 'success')
        return redirect(url_for('main.lab_home'))
    return render_template('crear_materia.html', title='Nueva Materia',
                            form=form, legend='Nueva Materia', area='Lab')

@materias.route("/lab/materia/<int:materia_id>")
@login_required
def lab_materia(materia_id):
    check_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    return render_template('materia.html', title=materia.nombre, materia=materia, area='Lab', user=current_user)

@materias.route("/lab/materia/<int:materia_id>/alerta", methods=['GET', 'POST'])
@login_required
def lab_alerta_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    form = ModBajoStockForm()
    if form.validate_on_submit():
        materia.bajo_stock = form.bajo_stock.data
        db.session.commit()
        flash('Actualizada la cantidad para la alerta de bajo stock', 'success')
        return redirect(url_for('materias.lab_materia', materia_id=materia.id))
    return render_template('modificar_alerta.html', form=form, legend='Modifica Alerta', area='Lab', materia=materia)

@materias.route("/lab/home/materia")
@login_required
def lab_home_materia():
    check_lab()
    # materias = Materia.query.filter_by(area=Area.Lab).all() # Esta forma no tiene order_by
    materias = db.session.query(Materia).filter(Materia.area == Area.Lab.value).order_by(Materia.id).all()
    return render_template('ver_materias.html', materias=materias, area='Lab', user=current_user)

@materias.route("/lab/materia/<int:materia_id>/add", methods=['GET', 'POST'])
@login_required
def lab_add_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    form = AddMateriaForm()
    if form.validate_on_submit():
        materia.cantidad += form.cantidad.data
        historial = HistorialMaterias(observacion=form.observacion.data, cantidad=form.cantidad.data,
                                         materia=materia, user = current_user, tipo='Entrada', area=Area.Lab.value)
        db.session.add(historial)
        db.session.commit()
        historial_quimico = HistorialQuimicos(tipo='Materia',historial_materia = historial, fecha_registro = historial.fecha_registro, area=Area.Lab.value)
        db.session.add(historial_quimico)
        db.session.commit()
        flash('Se ha añadido la entrada de materia', 'success')
        return redirect(url_for('materias.lab_materia', materia_id=materia.id))
    return render_template('añadir_materia.html', title='Menu Materia', 
                            form=form, legend='Menu Materia', materia=materia, area='Lab')

@materias.route("/lab/materia/<int:materia_id>/historial", methods=['GET', 'POST'])
@login_required
def lab_historial_materia_especifico(materia_id):
    check_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    historiales = HistorialMaterias.query.filter_by(materia=materia).order_by(HistorialMaterias.fecha_registro.desc()).all()
    return render_template('historial_materia.html', title='Menu Historial Materia', legend='Menu Historial Materia', 
                            historiales=historiales, materia=materia, area='Lab')

@materias.route("/lab/materia/historial")
@login_required
def lab_historial_materias():
    check_lab()
    historiales = HistorialMaterias.query.filter_by(area=Area.Lab.value).order_by(HistorialMaterias.fecha_registro.desc()).all()
    return render_template('historial_total_materias.html', historiales=historiales, title='Historial Materias', area='Lab')

@materias.route("/lab/materia/<int:materia_id>/reduce", methods=['GET', 'POST'])
@login_required
def lab_reduce_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    form = ReduceMateriaForm()
    if form.validate_on_submit():
        if materia.cantidad - form.cantidad.data < 0:
            flash('No se puede dejar la cantidad en numeros negativos', 'danger')
            return redirect(url_for('materias.lab_reduce_materia', materia_id=materia.id))        
        materia.cantidad -= form.cantidad.data
        historial = HistorialMaterias(observacion=form.observacion.data, cantidad=form.cantidad.data, 
                                        materia=materia, user = current_user, tipo='Salida', area=Area.Lab.value)
        db.session.add(historial)
        db.session.commit()
        historial_quimico = HistorialQuimicos(tipo='Materia',historial_materia = historial, fecha_registro = historial.fecha_registro, area=Area.Lab.value)
        db.session.add(historial_quimico)
        db.session.commit()        
        flash('Se ha añadido la salida de materia', 'success')
        return redirect(url_for('materias.lab_materia', materia_id=materia.id))
    return render_template('salida_materia.html', title='Menu Materia', 
                            form=form, legend='Menu Materia', materia=materia, area='Lab')

@materias.route("/lab/materia/<int:materia_id>/delete", methods=['POST'])
@login_required
def lab_delete_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    if materia.formulas != []:
        flash('Esta materia es parte de una o más formulas. Si desea eliminarla por favor elimine la(s) formula(s) de la(s) que es parte', 'danger')
        return redirect(url_for('materias.lab_materia', materia_id = materia.id))
    historiales = HistorialMaterias.query.filter_by(materia_id=materia_id).all()
    quimicos = Quimico.query.filter_by(materia_id=materia_id).all()
    # Eliminar Tablas dependientes de Materia
    for historial in historiales:
        q_historiales = HistorialQuimicos.query.filter_by(materia_id=historial.id).all()
        for q_historial in q_historiales:
            db.session.delete(q_historial)
        db.session.delete(historial)
    for quimico in quimicos:
        db.session.delete(quimico)
    db.session.delete(materia)
    db.session.commit()
    flash('La materia se ha eliminado', 'success')
    return redirect(url_for('main.lab_home'))

# ----------------------------------------------------------------------------------------------------------


# --------------------------------SECTOR DE ROUTES BODEGA---------------------------------------------------

@materias.route("/bod/materia/create", methods=['GET', 'POST'])
@login_required
def bod_new_materia():
    check_only_bod()
    form = MateriaForm()
    if form.validate_on_submit():
        materia = Materia(nombre=form.nombre.data, codigo=form.codigo.data, medida=form.medida.data, 
                            bajo_stock=form.bajo_stock.data, area=Area.Bod.value)
        db.session.add(materia)
        db.session.commit()
        quimico = Quimico(tipo='Materia', materia=materia, area=Area.Bod.value)
        db.session.add(quimico)
        db.session.commit()        
        flash('La materia se ha creado exitosamente!', 'success')
        return redirect(url_for('main.bod_home'))
    return render_template('crear_materia.html', title='Nueva Materia',
                            form=form, legend='Nueva Materia', area='Bod')

@materias.route("/bod/materia/<int:materia_id>")
@login_required
def bod_materia(materia_id):
    check_bod()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Bod.value:
        return abort(403)
    return render_template('materia.html', title=materia.nombre, materia=materia, area='Bod', user=current_user)

@materias.route("/bod/materia/<int:materia_id>/alerta", methods=['GET', 'POST'])
@login_required
def bod_alerta_materia(materia_id):
    check_only_bod()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Bod.value:
        return abort(403)
    form = ModBajoStockForm()
    if form.validate_on_submit():
        materia.bajo_stock = form.bajo_stock.data
        db.session.commit()
        flash('Actualizada la cantidad para la alerta de bajo stock', 'success')

flasksystem/templates/lab/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="mt-3 mb-3">
        <a href="{{ url_for('main.lab_home_historial') }}">
            <button type="button" class="btn btn-outline-info">Historial</button>
        </a>
    </div>
{% endblock content %}
{% block table %}
    <h2 class="text-center">Inventario</h2>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Busca por nombre. . .">
            </div>
        </div>
    </main>
            
    <div class="table-responsive">
        <table class="table table-bordered table-hover", id="myTable">
            <thead>
                <tr>
                    <th class ="home" onclick="sortTable(0)">Id</th>
                    <th class ="home" onclick="sortTable(1)">Nombre</th>
                    <th class ="home" onclick="sortTable(2)">Codigo</th>
                    <th class ="home" onclick="sortTable(3)">Tipo</th>
                    <th class ="home" onclick="sortTable(4)">Cantidad</th>
                    <th class="text-right">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for quimico in quimicos %}
                    {% if quimico.tipo == 'Materia' %}
                    {% if (quimico.materia.cantidad <= quimico.materia.bajo_stock) and quimico.materia.historial   %}
                        <tr class="table-danger">
                    {% else %}
                        <tr>
                    {% endif %}
                            <td>Materia ID: {{ quimico.materia.id }}</td>
                            <td>{{ quimico.materia.nombre }}</td>
                            <td>{{ quimico.materia.codigo }}</td>
                            <td>{{ quimico.materia.tipo }}</td>
                            <td>{{ quimico.materia.cantidad }} {{ quimico.materia.medida }}</td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm mt-1 mb-1 mr-1" href="{{ url_for('materias.lab_materia', materia_id=quimico.materia.id) }}">Ver</a>
                                {% if user.area == 'Lab' %}
                                  <a class="btn btn-success btn-sm mt-1 mb-1 mr-1" href="{{ url_for('materias.lab_add_materia', materia_id=quimico.materia.id) }}">Entrada</a>
                                  <a class="btn btn-danger btn-sm mt-1 mb-1 mr-1" href="{{ url_for('materias.lab_reduce_materia', materia_id=quimico.materia.id) }}">Salida</a>
                                {% endif %}
                                <a class="btn btn-info btn-sm mt-1 mb-1 mr-1" href="{{ url_for('materias.lab_historial_materia_especifico', materia_id=quimico.materia.id) }}">Historial</a>
                            </td>
                        </tr>
                    {% else %}
                    {% if (quimico.reactivo.cantidad <= quimico.reactivo.bajo_stock) and quimico.reactivo.historial %}
                        <tr class="table-danger">
                    {% else %}
                        <tr>
                    {% endif %}
                            <td>Reactivo ID: {{ quimico.reactivo.id }}</td>
                            <td>{{ quimico.reactivo.nombre }}</td>
                            <td>{{ quimico.reactivo.codigo }}</td>
                            <td>{{ quimico.reactivo.tipo }}</td>
                            <td>{{ quimico.reactivo.cantidad }} {{ quimico.reactivo.medida }}</td>
                            <td class="text-right">
                                <a class="btn btn-primary btn-sm mt-1 mb-1 mr-1" href="{{ url_for('reactivos.lab_reactivo', reactivo_id=quimico.reactivo.id) }}">Ver</a>
                                {% if user.area == 'Lab' %}
                                <a class="btn btn-success btn-sm mt-1 mb-1 mr-1" href="{{ url_for('reactivos.lab_add_reactivo', reactivo_id=quimico.reactivo.id) }}">Entrada</a>
                                <a class="btn btn-success btn-sm mt-1 mb-1 mr-1" href="{{ url_for('reactivos.lab_entrada_reactivo', reactivo_id=quimico.reactivo.id) }}">Produccion</a>
                                <a class="btn btn-danger btn-sm mt-1 mb-1 mr-1" href="{{ url_for('reactivos.lab_reduce_reactivo', reactivo_id=quimico.reactivo.id) }}">Salida</a>
                                {% endif %}
                                <a class="btn btn-info btn-sm mt-1 mb-1 mr-1" href="{{ url_for('reactivos.lab_historial_reactivo_especifico', reactivo_id=quimico.reactivo.id) }}">Historial</a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function myFunction() {
          // Declare variables
          var input, filter, table, tr, td, i, txtValue;
          input = document.getElementById("myInput");
          filter = input.value.toUpperCase();
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");
        
          // Loop through all table rows, and hide those who don't match the search query
          for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
              txtValue = td.textContent || td.innerText;
              if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
              } else {
                tr[i].style.display = "none";
              }
            }
          }
        }
    </script>
    <script>
        function sortTable(n) {
          var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
          table = document.getElementById("myTable");
          switching = true;
          // Set the sorting direction to ascending:
          dir = "asc";
          /* Make a loop that will continue until
          no switching has been done: */
          while (switching) {
            // Start by saying: no switching is done:
            switching = false;
            rows = table.rows;
            /* Loop through all table rows (except the
            first, which contains table headers): */
            for (i = 1; i < (rows.length - 1); i++) {
              // Start by saying there should be no switching:
              shouldSwitch = false;
              /* Get the two elements you want to compare,
              one from current row and one from the next: */
              x = rows[i].getElementsByTagName("TD")[n];
              y = rows[i + 1].getElementsByTagName("TD")[n];
              /* Check if the two rows should switch place,
              based on the direction, asc or desc: */
              if (dir == "asc") {
                if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                  // If so, mark as a switch and break the loop:
                  shouldSwitch = true;
                  break;
                }
              } else if (dir == "desc") {
                if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                  // If so, mark as a switch and break the loop:
                  shouldSwitch = true;
                  break;
                }
              }
            }
            if (shouldSwitch) {
              /* If a switch has been marked, make the switch
              and mark that a switch has been done: */
              rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
              switching = true;
              // Each time a switch is done, increase this count by 1:
              switchcount ++;
            } else {
              /* If no switching has been done AND the direction is "asc",
              set the direction to "desc" and run the while loop again. */
              if (switchcount == 0 && dir == "asc") {
                dir = "desc";
                switching = true;
              }
            }
          }
        }
    </script>
{% endblock table %}