flasksystem/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError

class ModBajoStockForm(FlaskForm):
    bajo_stock = IntegerField(validators=[DataRequired()])
    submit = SubmitField('Ingresa')
    
    def validate_bajo_stock(self, bajo_stock):
        if bajo_stock.data <= 0:
            raise ValidationError('Ingresa una cantidad mayor a 0')
 

flasksystem/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flasksystem.config import Config
from flask_migrate import Migrate, MigrateCommand
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
migrate = Migrate()
ma = Marshmallow()

login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'

from flasksystem.main.routes import main
from flasksystem.materias.routes import materias
from flasksystem.reactivos.routes import reactivos
from flasksystem.users.routes import users
from flasksystem.errors.handlers import errors


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    ma.init_app(app)

    app.register_blueprint(main)
    app.register_blueprint(materias)
    app.register_blueprint(reactivos)
    app.register_blueprint(users)
    app.register_blueprint(errors)

    return app

flasksystem/materias/routes.py
from flask import render_template, url_for, flash, redirect, abort, jsonify, request, Blueprint
from flask_login import current_user, login_required
from flasksystem import db
from flasksystem.models import Materia, HistorialMaterias, Quimico, HistorialQuimicos, Area
from flasksystem.materias.forms import MateriaForm, AddMateriaForm, ReduceMateriaForm
from flasksystem.main.utils import check_bod, check_lab, check_only_bod, check_only_lab
from flasksystem.main.forms import ModBajoStockForm
from flasksystem.schema import (materia_schema, materias_schema, historial_materia_schema, historiales_materia_schema,
                                quimico_schema, quimicos_schema, historial_quimico_schema, historiales_quimico_schema,
                                materia_bajo_stock_schema)
from flasksystem.users.routes import token_required
from marshmallow import ValidationError

materias = Blueprint('materias', __name__)

# --------------------------------SECTOR DE ROUTES LABORATORIO----------------------------------------------

@materias.route("/lab/materia/create", methods=['GET', 'POST'])
@login_required
def lab_new_materia():
    check_only_lab()
    form = MateriaForm()
    if form.validate_on_submit():
        materia = Materia(nombre=form.nombre.data, codigo=form.codigo.data, medida=form.medida.data, 
                            bajo_stock=form.bajo_stock.data, area=Area.Lab.value)
        db.session.add(materia)
        db.session.commit()
        quimico = Quimico(tipo='Materia', materia=materia, area=Area.Lab.value)
        db.session.add(quimico)
        db.session.commit()        
        flash('La materia se ha creado exitosamente!', 'success')
        return redirect(url_for('main.lab_home'))
    return render_template('crear_materia.html', title='Nueva Materia',
                            form=form, legend='Nueva Materia', area='Lab')

@materias.route("/lab/materia/<int:materia_id>")
@login_required
def lab_materia(materia_id):
    check_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    return render_template('materia.html', title=materia.nombre, materia=materia, area='Lab', user=current_user)

@materias.route("/lab/materia/<int:materia_id>/alerta", methods=['GET', 'POST'])
@login_required
def lab_alerta_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    form = ModBajoStockForm()
    if form.validate_on_submit():
        materia.bajo_stock = form.bajo_stock.data
        db.session.commit()
        flash('Actualizada la cantidad para la alerta de bajo stock', 'success')
        return redirect(url_for('materias.lab_materia', materia_id=materia.id))
    return render_template('modificar_alerta.html', form=form, legend='Modifica Alerta', area='Lab', materia=materia)

@materias.route("/lab/home/materia")
@login_required
def lab_home_materia():
    check_lab()
    # materias = Materia.query.filter_by(area=Area.Lab).all() # Esta forma no tiene order_by
    materias = db.session.query(Materia).filter(Materia.area == Area.Lab.value).order_by(Materia.id).all()
    return render_template('ver_materias.html', materias=materias, area='Lab', user=current_user)

@materias.route("/lab/materia/<int:materia_id>/add", methods=['GET', 'POST'])
@login_required
def lab_add_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    form = AddMateriaForm()
    if form.validate_on_submit():
        materia.cantidad += form.cantidad.data
        historial = HistorialMaterias(observacion=form.observacion.data, cantidad=form.cantidad.data,
                                         materia=materia, user = current_user, tipo='Entrada', area=Area.Lab.value)
        db.session.add(historial)
        db.session.commit()
        historial_quimico = HistorialQuimicos(tipo='Materia',historial_materia = historial, fecha_registro = historial.fecha_registro, area=Area.Lab.value)
        db.session.add(historial_quimico)
        db.session.commit()
        flash('Se ha añadido la entrada de materia', 'success')
        return redirect(url_for('materias.lab_materia', materia_id=materia.id))
    return render_template('añadir_materia.html', title='Menu Materia', 
                            form=form, legend='Menu Materia', materia=materia, area='Lab')

@materias.route("/lab/materia/<int:materia_id>/historial", methods=['GET', 'POST'])
@login_required
def lab_historial_materia_especifico(materia_id):
    check_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    historiales = HistorialMaterias.query.filter_by(materia=materia).order_by(HistorialMaterias.fecha_registro.desc()).all()
    return render_template('historial_materia.html', title='Menu Historial Materia', legend='Menu Historial Materia', 
                            historiales=historiales, materia=materia, area='Lab')

@materias.route("/lab/materia/historial")
@login_required
def lab_historial_materias():
    check_lab()
    historiales = HistorialMaterias.query.filter_by(area=Area.Lab.value).order_by(HistorialMaterias.fecha_registro.desc()).all()
    return render_template('historial_total_materias.html', historiales=historiales, title='Historial Materias', area='Lab')

@materias.route("/lab/materia/<int:materia_id>/reduce", methods=['GET', 'POST'])
@login_required
def lab_reduce_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    form = ReduceMateriaForm()
    if form.validate_on_submit():
        if materia.cantidad - form.cantidad.data < 0:
            flash('No se puede dejar la cantidad en numeros negativos', 'danger')
            return redirect(url_for('materias.lab_reduce_materia', materia_id=materia.id))        
        materia.cantidad -= form.cantidad.data
        historial = HistorialMaterias(observacion=form.observacion.data, cantidad=form.cantidad.data, 
                                        materia=materia, user = current_user, tipo='Salida', area=Area.Lab.value)
        db.session.add(historial)
        db.session.commit()
        historial_quimico = HistorialQuimicos(tipo='Materia',historial_materia = historial, fecha_registro = historial.fecha_registro, area=Area.Lab.value)
        db.session.add(historial_quimico)
        db.session.commit()        
        flash('Se ha añadido la salida de materia', 'success')
        return redirect(url_for('materias.lab_materia', materia_id=materia.id))
    return render_template('salida_materia.html', title='Menu Materia', 
                            form=form, legend='Menu Materia', materia=materia, area='Lab')

@materias.route("/lab/materia/<int:materia_id>/delete", methods=['POST'])
@login_required
def lab_delete_materia(materia_id):
    check_only_lab()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Lab.value:
        return abort(403)
    if materia.formulas != []:
        flash('Esta materia es parte de una o más formulas. Si desea eliminarla por favor elimine la(s) formula(s) de la(s) que es parte', 'danger')
        return redirect(url_for('materias.lab_materia', materia_id = materia.id))
    historiales = HistorialMaterias.query.filter_by(materia_id=materia_id).all()
    quimicos = Quimico.query.filter_by(materia_id=materia_id).all()
    # Eliminar Tablas dependientes de Materia
    for historial in historiales:
        q_historiales = HistorialQuimicos.query.filter_by(materia_id=historial.id).all()
        for q_historial in q_historiales:
            db.session.delete(q_historial)
        db.session.delete(historial)
    for quimico in quimicos:
        db.session.delete(quimico)
    db.session.delete(materia)
    db.session.commit()
    flash('La materia se ha eliminado', 'success')
    return redirect(url_for('main.lab_home'))

# ----------------------------------------------------------------------------------------------------------


# --------------------------------SECTOR DE ROUTES BODEGA---------------------------------------------------

@materias.route("/bod/materia/create", methods=['GET', 'POST'])
@login_required
def bod_new_materia():
    check_only_bod()
    form = MateriaForm()
    if form.validate_on_submit():
        materia = Materia(nombre=form.nombre.data, codigo=form.codigo.data, medida=form.medida.data, 
                            bajo_stock=form.bajo_stock.data, area=Area.Bod.value)
        db.session.add(materia)
        db.session.commit()
        quimico = Quimico(tipo='Materia', materia=materia, area=Area.Bod.value)
        db.session.add(quimico)
        db.session.commit()        
        flash('La materia se ha creado exitosamente!', 'success')
        return redirect(url_for('main.bod_home'))
    return render_template('crear_materia.html', title='Nueva Materia',
                            form=form, legend='Nueva Materia', area='Bod')

@materias.route("/bod/materia/<int:materia_id>")
@login_required
def bod_materia(materia_id):
    check_bod()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Bod.value:
        return abort(403)
    return render_template('materia.html', title=materia.nombre, materia=materia, area='Bod', user=current_user)

@materias.route("/bod/materia/<int:materia_id>/alerta", methods=['GET', 'POST'])
@login_required
def bod_alerta_materia(materia_id):
    check_only_bod()
    materia = Materia.query.get_or_404(materia_id)
    if materia.area != Area.Bod.value:
        return abort(403)
    form = ModBajoStockForm()
    if form.validate_on_submit():
        materia.bajo_stock = form.bajo_stock.data
        db.session.commit()
        flash('Actualizada la cantidad para la alerta de bajo stock', 'success')

flasksystem/users/routes.py
import enum
import jwt
import datetime
import os
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify, make_response
from flask_login import login_user, current_user, logout_user, login_required
from flasksystem import db, bcrypt
from flasksystem.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, UpdatePasswordForm
from flasksystem.models import User
from flasksystem.schema import user_schema
from functools import wraps
from sqlalchemy import or_

users = Blueprint('users', __name__)

def token_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token = None

        if 'x-access-token' in request.headers:
            token = request.headers['x-access-token']
        
        if not token:
            return jsonify({'mensaje': 'No se encuentra el token!'}), 401
        
        try:
            data = jwt.decode(token, os.environ.get('SECRET_KEY'))
            usuario_actual = User.query.filter_by(id=data['id']).first()
        except:
            return jsonify({'mensaje': 'El token es invalido!'}), 401

        return f(usuario_actual, *args, **kwargs)
        
    return decorated

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data.lower(), password=hashed_password, area=form.area.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! you are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)
    

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        print(form.password.data)
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    flash('You have Log out', 'info')
    return redirect(url_for('main.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)

@users.route("/account/password", methods=['GET', 'POST'])
@login_required
def password():
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        current_user.password = hashed_password
        db.session.commit()
        flash('Contraseña actualizada con exito', 'success')
        return redirect(url_for('users.account'))
    return render_template('password.html', form=form, legend='Cambiar contraseña')

# ---------------------------------------------------------------------------------------------


@users.route("/json/login", methods=['POST'])
def json_login():
    auth = request.authorization

    if not auth or not auth.username or not auth.password:
        return make_response('No se pudo verificar', 401, {'WWW-Authenticate': 'Basic realm="Login Required!"'})
    
    user = User.query.filter_by(email=auth.username).first()
    
    if not user:
        return make_response('No se pudo verificar', 401, {'WWW-Authenticate': 'Basic realm="Login Required!"'})
    
    if bcrypt.check_password_hash(user.password, auth.password):
        token = jwt.encode({'id' : user.id, 'exp' : datetime.datetime.utcnow() + datetime.timedelta(minutes=30)}, os.environ.get('SECRET_KEY'))
        return jsonify({"token" : token.decode("UTF-8")})
    
    return make_response('No se pudo verificar', 401, {'WWW-Authenticate': 'Basic realm="Login Required!"'})

@users.route("/json/register", methods=['POST'])
def json_register():
    try:
        username = request.json['username']
        email = request.json['email']
        password = request.json['password']
        area = request.json['area']
    except:
        return jsonify({"mensaje": "Json invalido"}), 422
    exist = db.session.query(User).filter(or_(User.username==username, User.email==email)).first()
    if exist:
        return jsonify({"mensaje": "Un usuario con el username o email ingresado ya esta registrado"})
    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
    user = User(username=username, email=email.lower(), password=hashed_password, area=area)
    db.session.add(user)
    db.session.commit()
    return user_schema.jsonify(user)

flasksystem/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flasksystem/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<div class="media-body">
				<h2 class="account-heading">{{ current_user.username }} | {{ current_user.email }}</h2>
				<br/>
			</div>
		</div>
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-botom mb-4">Actualizar Info</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>			  
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<a href="{{ url_for('users.password') }}">
					<button type="button" class="btn btn-outline-info">Cambiar Contraseña</button>
				</a>
			</div>
		</form>
	</div>
{% endblock content %}

flasksystem/templates/alerta_materia.html
{% extends "layout.html" %}
{% block content %}

    <article class="media content-section">
        <div class="media-body">
            {% if area == 'Lab' %}
                <h2 class="article-title"><a href="{{ url_for('materias.lab_materia', materia_id=materia.id) }}">{{ materia.nombre }}</a></h2>}
            {% elif area == 'Bod' %}
                <h2 class="article-title"><a href="{{ url_for('materias.bod_materia', materia_id=materia.id) }}">{{ materia.nombre }}</a></h2>
            {% endif %}
            <p class="article-content">Codigo:   {{ materia.codigo }}</p>
            <p class="article-content">Alerta Actual:    {{ materia.bajo_stock }} {{ materia.medida }}</p>
        </div>
    </article>   

    <div class="marca-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-botom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.bajo_stock.label(class="form-control-label") }}

                    {% if form.bajo_stock.errors %}
                        {{ form.bajo_stock(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.bajo_stock.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.bajo_stock(class="form-control form-control-lg") }}
                    {% endif %}
                    
                </div>               
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flasksystem/templates/añadir_materia.html
{% extends "layout.html" %}
{% block content %}

    <div class="article-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-botom mb-4">{{ legend }}</legend>
                <article class="media content-section">
                    <div class="media-body">
                        {% if area == 'Lab' %}
                            <h2 class="article-title"><a href="{{ url_for('materias.lab_materia', materia_id=materia.id) }}">{{ materia.nombre }}</a></h2>
                        {% elif area == 'Bod' %}
                            <h2 class="article-title"><a href="{{ url_for('materias.bod_materia', materia_id=materia.id) }}">{{ materia.nombre }}</a></h2>
                        {% endif %}
                        <p class="article-content">Codigo:   {{ materia.codigo }}</p>
                        <p class="article-content">Cantidad Actual:    {{ materia.cantidad }} {{ materia.medida }}</p>
                    </div>
                </article>                
                <div class="form-group">
                    {{ form.cantidad.label(class="form-control-label") }}

                    {% if form.cantidad.errors %}
                        {{ form.cantidad(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.cantidad.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.cantidad(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.observacion.label(class="form-control-label") }}

                    {% if form.observacion.errors %}
                        {{ form.observacion(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.observacion.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.observacion(class="form-control form-control-lg") }}
                    {% endif %}
                    
                </div>             
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

flasksystem/templates/historial_base.html
{% extends "layout.html" %}

{% block content %}

    {% block menu %}{% endblock menu %}

{% endblock content %}

{% block table %}
    <h2 class="text-center">{{title}}</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <!-- <th>Id</th> -->
                    <th>Tipo</th>
                    <th>Nombre</th>
                    <th>Codigo</th>
                    <th>Cantidad</th>
                    <th>Usuario</th>
                    <th>Fecha</th>
                    <th>Observacion</th>
                    <th class="text-right">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% block historial %}{% endblock historial %}
            </tbody>
        </table>
    </div>
{% endblock table %}

flasksystem/templates/historial_materia.html
{% extends "layout.html" %}
{% block content %}
        {% if area == 'Lab' %}
            <article class="media content-section">
                <div class="media-body">
                    <h2 class="article-title"><a href="{{ url_for('materias.lab_materia', materia_id=materia.id) }}">{{ materia.nombre }}</a></h2>
                    <p class="article-content">Id:   {{ materia.id }}</p>
                    <p class="article-content">Codigo:   {{ materia.codigo }}</p>
                    <p class="article-content">Cantidad Actual:    {{ materia.cantidad }} {{ materia.medida }}</p>
                </div>
                </article>
        {% elif area == 'Bod' %}
            <article class="media content-section">
                <div class="media-body">
                    <h2 class="article-title"><a href="{{ url_for('materias.bod_materia', materia_id=materia.id) }}">{{ materia.nombre }}</a></h2>
                    <p class="article-content">Id:   {{ materia.id }}</p>
                    <p class="article-content">Codigo:   {{ materia.codigo }}</p>
                    <p class="article-content">Cantidad Actual:    {{ materia.cantidad }} {{ materia.medida }}</p>
                </div>
                </article>
        {% endif %}

{% endblock content %}

{% block table %}
    <h2 class="text-center">Historial</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Tipo</th>
                    <th>Nombre</th>
                    <th>Codigo</th>
                    <th>Cantidad</th>
                    <th>Usuario</th>
                    <th>Fecha</th>
                    <th>Observacion</th>
                </tr>
            </thead>
            <tbody>
                {% for historial in historiales %}
                    <tr>
                        <td>{{ historial.tipo }}</td>
                        <td>{{ historial.materia.nombre }}</td>
                        <td>{{ historial.materia.codigo }}</td>
                        {% if historial.tipo == 'Entrada' %}
                            <td>+{{ historial.cantidad }} {{ historial.materia.medida }}</td>
                        {% else %}
                            <td>-{{ historial.cantidad }} {{ historial.materia.medida }}</td>
                        {% endif %}
                        <td>{{ historial.user.username }} | {{ historial.user.email }}</td>
                        <td>{{ historial.fecha_registro.strftime('%d-%m-%Y   %H:%M:%S') }}</td>
                        <td>{{ historial.observacion }}</td> 
                    </tr>
                {% endfor %}                
            </tbody>
        </table>
    </div>    

{% endblock table %}

flasksystem/templates/index.html
{% extends "layout.html" %}
{% block table %}
    <img class="rounded mx-auto d-block" alt="..." src="{{ url_for('static', filename='profile_pics/logo-quinova-trasparente2.png') }}">
{% endblock table %}

flasksystem/templates/ver_historial.html
{% extends "historial_base_total.html" %}
{% block menu %}

{% endblock menu %}
{% block historial %}
    <h2 class="text-center">{{ title }}</h2>
    <div class="table-responsive">
        {% for historial in historiales %}
            {% if historial.tipo == 'Materia' %}
                <tr>
                    <td>-</td>
                    <td>{{ historial.historial_materia.tipo }}</td>
                    <td>{{ historial.historial_materia.materia.nombre }}</td>
                    <td>{{ historial.historial_materia.materia.codigo }}</td>
                    <td>{{ historial.tipo }}</td>
                    {% if historial.historial_materia.tipo == 'Entrada' %}
                        <td>+{{ historial.historial_materia.cantidad }} {{ historial.historial_materia.materia.medida }}</td>
                    {% else %}
                        <td>-{{ historial.historial_materia.cantidad }} {{ historial.historial_materia.materia.medida }}</td>
                    {% endif %}
                    <td>{{ historial.historial_materia.user.username }} | {{ historial.historial_materia.user.email }}</td>
                    <td>{{ historial.historial_materia.fecha_registro.strftime('%d-%m-%Y   %H:%M:%S') }}</td>
                    <td>{{ historial.historial_materia.observacion }}</td>
                    <td class="text-right">
                        {% if area == 'Lab' %}
                            <a class="btn btn-outline-primary btn-sm" href="{{ url_for('materias.lab_materia', materia_id=historial.historial_materia.materia.id) }}">Ver</a>                         
                        {% elif area == 'Bod' %}
                            <a class="btn btn-outline-primary btn-sm" href="{{ url_for('materias.bod_materia', materia_id=historial.historial_materia.materia.id) }}">Ver</a>                         
                        {% endif %}
                        
                    </td>
                </tr>
            {% else %}
                {% if historial.tipo == 'Reactivo' %}
                    <tr>
                        {% if historial.historial_reactivo.tipo == 'Salida' or historial.historial_reactivo.tipo == 'Produccion' %}
                            <td>{{ historial.historial_reactivo.lote }}</td>
                        {% else %}
                            <td>-</td>
                        {% endif %} 
                        <td>{{ historial.historial_reactivo.tipo }}</td>
                        <td>{{ historial.historial_reactivo.reactivo.nombre }}</td>
                        <td>{{ historial.historial_reactivo.reactivo.codigo }}</td>
                        <td>{{ historial.tipo }}</td>
                        {% if historial.historial_reactivo.tipo == 'Salida' %}
                            <td>-{{ historial.historial_reactivo.cantidad }} {{ historial.historial_reactivo.reactivo.medida }}</td>
                        {% else %}
                            <td>+{{ historial.historial_reactivo.cantidad }} {{ historial.historial_reactivo.reactivo.medida }}</td>
                        {% endif %}
                        <td>{{ historial.historial_reactivo.user.username }} | {{ historial.historial_reactivo.user.email }}</td>
                        <td>{{ historial.historial_reactivo.fecha_registro.strftime('%d-%m-%Y   %H:%M:%S') }}</td>
                        <td>{{ historial.historial_reactivo.observacion }}</td>
                        <td class="text-right">
                            {% if area == 'Lab' %}
                                <a class="btn btn-outline-primary btn-sm" href="{{ url_for('reactivos.lab_reactivo', reactivo_id=historial.historial_reactivo.reactivo.id) }}">Ver</a>                  
                            {% elif area == 'Bod' %}
                                <a class="btn btn-outline-primary btn-sm" href="{{ url_for('reactivos.bod_reactivo', reactivo_id=historial.historial_reactivo.reactivo.id) }}">Ver</a>                  
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock historial %}